name: Run Playwright tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ­ Install Playwright browsers
        run: npx playwright install --with-deps

      - name: ğŸš€ Start the app
        run: yarn web &
        env:
          BROWSER: none
        # Wait for the app to be ready
      - name: â± Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: https://bsky.app/
          timeout: 60

      - name: ğŸ§ª Run Playwright tests
        run: yarn test:e2e

      - name: Generate Allure report
        run: |
          yarn allure generate allure-results --clean
          yarn allure open allure-report